build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank accounts related Prod APIs "
  contactDetails:
    name: "Joe Dave - Developer"
    email: "joe@eazybank.com"
  onCallSupport:
    - (555) 555-1238
    - (555) 523-1349