build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smith Doe - Developer"
    email: "smith@eazybank.com"
  onCallSupport:
    - (555) 555-1236
    - (555) 523-1347