build:
  version: "3.0"
cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1231
    - (555) 523-13452