build:
  version: "1.0"
cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1233
    - (555) 523-13453